version: "3"
services:
  client:
    build: "./client"
    ports:
      - "3000:3000"
    command: "npm run start"

  order:
    build: "./order"
    ports:
      - "3001:3000"

  payment:
    build: "./payment"
    ports:
      - "3002:3000"
